### ISSUE TITLE
open-isns needs to install headers and library for use by other package

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-isns#1]
open-isns needs to install "public" header files (those used by other packages), and it's library files (libisns.a) so that others (like open-iscsi) can use them.

This is in preparation for the open-iscsi / open-isns split.

**Comment by ls-zhu** [comment]
I think it is needed, I am facing such problems today when build open-iscsi, I copied libisns.a and the header files manually

**Comment by gonzoleeman** [comment]
I believe I should have closed this issue, as it has been resolved. See Makefile.in, which now has targets install_lib and install_hdrs. Do you need more than what is provided there?

**Comment by gonzoleeman** [comment]
I believe this is fixed now, in version v0.95. Use "make install_hdrs" to install header files in /usr/include/isns, and use "make install_lib" to install the archive file (libisns.a) in /usr/lib.
