### ISSUE TITLE
can't build without openssl headers?

### ISSUE THREAD

**Issue by SvenDowideit** [open-iscsi/open-isns#12]
The readme implies that its an optional dependency, but:

```
checking for locale.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for socket in -lsocket... no
checking for getopt_long... yes
checking openssl/crypto.h usability... no
checking openssl/crypto.h presence... no
checking for openssl/crypto.h... no
checking for EVP_PKEY_new in -lcrypto... no
checking slp.h usability... no
checking slp.h presence... no
checking for slp.h... no
checking for SLPOpen in -lslp... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/libisns/paths.h
config.status: creating config.h
config.status: config.h is unchanged
root@sven-machine:/dist/isns# make
gcc -Wall -fno-strict-aliasing -g -O2 -I. -Iinclude -D_GNU_SOURCE  -c -o server.o server.c
In file included from server.c:10:0:
security.h:10:25: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
                         ^
compilation terminated.
<builtin>: recipe for target 'server.o' failed
make: *** [server.o] Error 1
```

**Comment by gonzoleeman** [comment]
I have looked at this code, in response to this issue. It looks to me like the original intent was to make the openssl package completely optional, but that certainly isn't the case now. Even having "--with-security=no" when configuring, it still seems to require the openssl development package, to include evp.h and it's types.

In looking at the security code, I can see I don't know it's contents at all. So I cannot easily say if it would be simple to remove this dependency. This is complicated by the fact that I rarely use open-isns these days and when I do I never use security.

If you can come up with an update that makes openssl optional and also of course does not break the security when used, I'd be glad to help you review and test that.

Alternatively, if making openssl optional is not a goal for you, then we could update the README and ChangeLog files to reflect the fact that openssl is required even when building without security/crypto.

**Comment by gonzoleeman** [comment]
Sven, if you're still around and interested, I've updated the code to build and test without security. It avoids including libcrypto. All the tests were updated to pass, but I didn't do any manual functional testing.

Would you like to test my branch before I commit it?

**Comment by gonzoleeman** [comment]
Okay, I pushed these changes so that everything builds and passes tests if you pass the option "--with-security=no" to configure. I did not do any real functional testing of my own, but I believe as long as you run without any authentication it will work in this case. Closing this issue.
