### ISSUE TITLE
isnsadm deregister

### ISSUE THREAD

**Issue by GTAdoum** [open-iscsi/open-isns#28]
Hello,
I tried to register, it works but so far did not figure out how to specify the portal to attach to a target registered.  Then I try to deregister so I could try another registration with different parameters, but none of the attributes given are accepted.  What is the proper way to deregister a target on the iSNS server with isnsadm command?  I tried attributes: iscsi-name, eid, iscsi-alias, target.  I also tried registering with --replace but always returns the same error, Invalid registration.
It would be nice that the deregister command is the same command syntax as register, this way we can recall the register command line, add the "de" and execute it.

**Comment by gonzoleeman** [comment]
Please show your exact command sequence. And the output from "isnsd --dump-db" at each stage?

**Comment by gonzoleeman** [comment]
No response, so closing the issue. Please re-open if this is still a problem for you.
