### ISSUE TITLE
make systemd optional

### ISSUE THREAD

**Issue by ktdreyer** [open-iscsi/open-isns#3]
Would it be possible to make the dependency on systemd optional? This would allow me to build packages for Ubuntu Trusty (since that distro does not yet have a libsystemd-dev package.)

**Comment by ktdreyer** [comment]
@phatina , would it be possible to make this optional, to support open-isns on Trusty?

**Comment by phatina** [comment]
@ktdreyer, try this [PPA](https://launchpad.net/~phatina/+archive/ubuntu/isns-utils-nosystemd)...

**Comment by gonzoleeman** [comment]
@ktdreyer , yes we could make systemd optional. The only effect it has is on the socket opening at startup. We could either make it a compile-time or run-time option. I'm thinking compile-time, since the environment (systemd or no systemd) doesn't change dynamically.

**Comment by gonzoleeman** [comment]
@ktdreyer - do you still care? I will be glad to submit a change that will make systemd optional, but no need to do that if nobody cares ...

**Comment by ktdreyer** [comment]
Thanks @phatina and @gonzoleeman . As it turns out, I will just build the package for Ubuntu Xenial and run them on that distro. I really appreciate your feedback on this and especially that PPA work.
