### ISSUE TITLE
isnsd initialization error

### ISSUE THREAD

**Issue by rickysarraf** [open-iscsi/open-isns#31]
### Description

I recently pitched in to update `open-isns` in Debian. Up till now, the version we had in Debian is `0.97`. The other maintainer, `Christian Seiler`, had done a fantastic work on that release in Debian. IIRC, he's the one who introduced the package in Debian, in the first place. But he's been MIA for some time now and thus I intend to just keep open-isns up-to-date in Debian.

I really am not well versed with open-isns nor do I intend to, given my limited time. That is why this bug report.

In the `0.97` version of open-isns, we have a post-installation script in the package, which invokes the `isnsd --init` command. In the new  `0.100` version that I updated very recently, I enabled the linking with the OpenSSL library, something that we've had been avoiding in Debian for quite some time due to lack of clarity. But now, there's some clarity and thus I enabled the linking to openssl.

So, when the post-installation script is invoked, I get the following error:

```
rrs@priyasi:~/.../debian (debian/master)$ sudo apt install open-isns-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libisns0 open-isns-discoveryd open-isns-utils
The following NEW packages will be installed:
  libisns0 open-isns-discoveryd open-isns-server open-isns-utils
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/176 kB of archives.
After this operation, 780 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Retrieving bug reports... Done
Parsing Found/Fixed information... Done
Preconfiguring packages ...
Selecting previously unselected package libisns0:amd64.
(Reading database ... 416129 files and directories currently installed.)
Preparing to unpack .../libisns0_0.100-2_amd64.deb ...
Unpacking libisns0:amd64 (0.100-2) ...
Selecting previously unselected package open-isns-utils.
Preparing to unpack .../open-isns-utils_0.100-2_amd64.deb ...
Unpacking open-isns-utils (0.100-2) ...
Selecting previously unselected package open-isns-discoveryd.
Preparing to unpack .../open-isns-discoveryd_0.100-2_amd64.deb ...
Unpacking open-isns-discoveryd (0.100-2) ...
Selecting previously unselected package open-isns-server.
Preparing to unpack .../open-isns-server_0.100-2_amd64.deb ...
Unpacking open-isns-server (0.100-2) ...
Setting up libisns0:amd64 (0.100-2) ...
Setting up open-isns-utils (0.100-2) ...
Setting up open-isns-server (0.100-2) ...
/etc/iscsi/initiatorname.iscsi: No such file or directory
Generating DSA parameters; this may take a while
+
Warning: Error generating DSA parameters - OpenSSL errors follow:
dpkg: error processing package open-isns-server (--configure):
 installed open-isns-server package post-installation script subprocess returned error exit status 1
Setting up open-isns-discoveryd (0.100-2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/isnsdd.service → /lib/systemd/system/isnsdd.service.
Processing triggers for man-db (2.9.3-2) ...
Processing triggers for libc-bin (2.31-4) ...
Errors were encountered while processing:
 open-isns-server
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
14:42 ♒ ॐ ♅ ⛢   ☹ 😟=> 100  
```

First of all, the file that the `isnsd` daemon is expecting comes from `open-iscsi`. It doesn't even come from the iscsi package but is rather generated. 

So:
* is the `open-iscsi` daemon a dependency ? 
* Or is it just that iscsi's presence makes this package more featureful ?

Manually invoking the `isnsd --init` command throws openssl errors. 

```
rrs@priyasi:~/.../debian (debian/master)$ sudo isnsd --init
/etc/iscsi/initiatorname.iscsi: No such file or directory
Warning: Error loading DSA parameters - OpenSSL errors follow:
Warning: > get_name: no start line
Warning: Failed to generate AuthKey
14:43 ♒ ॐ ♅ ⛢   ☹ 😟=> 1
```

I have been contemplating if I should just drop the post-installation script that runs this initialization and delegate this task to the user, on how they'd need to configure this daemon carefully. But then, in Debian, that standard expectation is that if you install a daemon, it is mostly active the moment the installation procedure is complete, which is what Christian did initially for this tool.

**Comment by gonzoleeman** [comment]
> On Nov 24, 2020, at 7:28 AM, Ritesh Raj Sarraf <notifications@github.com> wrote:
> 
> 
> Description
> 
> I recently pitched in to update open-isns in Debian. Up till now, the version we had in Debian is 0.97. The other maintainer, Christian Seiler, had done a fantastic work on that release in Debian. IIRC, he's the one who introduced the package in Debian, in the first place. But he's been MIA for some time now and thus I intend to just keep open-isns up-to-date in Debian.
> 
> I really am not well versed with open-isns nor do I intend to, given my limited time. That is why this bug report.
> 
> In the 0.97 version of open-isns, we have a post-installation script in the package, which invokes the isnsd --init command. In the new 0.100 version that I updated very recently, I enabled the linking with the OpenSSL library, something that we've had been avoiding in Debian for quite some time due to lack of clarity. But now, there's some clarity and thus I enabled the linking to openssl.
> 
> So, when the post-installation script is invoked, I get the following error:
> 
> rrs@priyasi:~/.../debian (debian/master)$ sudo apt install open-isns-server
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following additional packages will be installed:
>   libisns0 open-isns-discoveryd open-isns-utils
> The following NEW packages will be installed:
>   libisns0 open-isns-discoveryd open-isns-server open-isns-utils
> 0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
> Need to get 0 B/176 kB of archives.
> After this operation, 780 kB of additional disk space will be used.
> Do you want to continue? [Y/n] 
> Retrieving bug reports... Done
> Parsing Found/Fixed information... Done
> Preconfiguring packages ...
> Selecting previously unselected package libisns0:amd64.
> (Reading database ... 416129 files and directories currently installed.)
> Preparing to unpack .../libisns0_0.100-2_amd64.deb ...
> Unpacking libisns0:amd64 (0.100-2) ...
> Selecting previously unselected package open-isns-utils.
> Preparing to unpack .../open-isns-utils_0.100-2_amd64.deb ...
> Unpacking open-isns-utils (0.100-2) ...
> Selecting previously unselected package open-isns-discoveryd.
> Preparing to unpack .../open-isns-discoveryd_0.100-2_amd64.deb ...
> Unpacking open-isns-discoveryd (0.100-2) ...
> Selecting previously unselected package open-isns-server.
> Preparing to unpack .../open-isns-server_0.100-2_amd64.deb ...
> Unpacking open-isns-server (0.100-2) ...
> Setting up libisns0:amd64 (0.100-2) ...
> Setting up open-isns-utils (0.100-2) ...
> Setting up open-isns-server (0.100-2) ...
> /etc/iscsi/initiatorname.iscsi: No such file or directory
> Generating DSA parameters; this may take a while
> +
> Warning: Error generating DSA parameters - OpenSSL errors follow:
> dpkg: error processing package open-isns-server (--configure):
>  installed open-isns-server package post-installation script subprocess returned error exit status 1
> Setting up open-isns-discoveryd (0.100-2) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/isnsdd.service → /lib/systemd/system/isnsdd.service.
> Processing triggers for man-db (2.9.3-2) ...
> Processing triggers for libc-bin (2.31-4) ...
> Errors were encountered while processing:
>  open-isns-server
> needrestart is being skipped since dpkg has failed
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 14:42 ♒ ॐ ♅ ⛢   ☹ 😟=> 100  
> First of all, the file that the isnsd daemon is expecting comes from open-iscsi. It doesn't even come from the iscsi package but is rather generated.
> 
> So:
> 
> is the open-iscsi daemon a dependency ?
> Or is it just that iscsi's presence makes this package more featureful ?
> Manually invoking the isnsd --init command throws openssl errors.
> 
> rrs@priyasi:~/.../debian (debian/master)$ sudo isnsd --init
> /etc/iscsi/initiatorname.iscsi: No such file or directory
> Warning: Error loading DSA parameters - OpenSSL errors follow:
> Warning: > get_name: no start line
> Warning: Failed to generate AuthKey
> 14:43 ♒ ॐ ♅ ⛢   ☹ 😟=> 1
> I have been contemplating if I should just drop the post-installation script that runs this initialization and delegate this task to the user, on how they'd need to configure this daemon carefully. But then, in Debian, that standard expectation is that if you install a daemon, it is mostly active the moment the installation procedure is complete, which is what Christian did initially for this tool.
> 
> 

Raj, I don’t think I can help you, at least not with the information you supplied.

It looks like something in the post-install script is not working, but I don’t have access to those package sources, so I have no idea what it’s trying to do that fails.

Yes, open-isns uses the iSCSI initiator name, if none is supplied in the configuration file. So you can set an initiator name there when you install open-isns, but it would have to be based on the hostname or MAC address of the system it’s being installed on so it’s not the same on every system (much like the way ithe open-iscsi IQN is created when open-iscsi is installed).

I just installed open-isns-discoveryd on a debian VM, and it asked me questions like “what is your initiator name” (I don’t have open-iscsi installed on this system), so I’m not sure how you’d handle that question at install time.

I suggest you file a bug with debian, since this seems to be a packaging issue, and every distro does their packaging differently.

— 
Lee Duncan

**Comment by rickysarraf** [comment]
@gonzoleeman The post-installation script runs just the `isnsd --init` command, as exampled below. Which is what is failing.
So does the `isnsd` daemon need a special pre-setup environment before it should be initialized ?

```
rrs@priyasi:~/.../debian (debian/master)$ sudo isnsd --init
/etc/iscsi/initiatorname.iscsi: No such file or directory
Warning: Error loading DSA parameters - OpenSSL errors follow:
Warning: > get_name: no start line
Warning: Failed to generate AuthKey
14:43 ♒ ॐ ♅ ⛢   ☹ 😟=> 1
```

**Comment by gonzoleeman** [comment]
> On Dec 2, 2020, at 7:35 AM, Ritesh Raj Sarraf <notifications@github.com> wrote:
> 
> 
> @gonzoleeman <https://github.com/gonzoleeman> The post-installation script runs just the isnsd --init command, as exampled below. Which is what is failing.
> So does the isnsd daemon need a special pre-setup environment before it should be initialized ?
> 
> rrs@priyasi:~/.../debian (debian/master)$ sudo isnsd --init
> /etc/iscsi/initiatorname.iscsi: No such file or directory
> Warning: Error loading DSA parameters - OpenSSL errors follow:
> Warning: > get_name: no start line
> Warning: Failed to generate AuthKey
> 14:43 ♒ ॐ ♅ ⛢   ☹ 😟=> 1

Yes, for initialization to complete, you need an initiator name. There are two ways to tell it your initiator name:

1. Populate the file /etc/iscsi/initiatorname.iscsi, or

2. Set the “SourceName” attribute in /etc/isns/isnsd.conf

If you have both, I believe the one in isnsd.conf is used, which is why it is commented out by default. There is no way to pass in an attribute in order to set this SourceName value on the fly.

So to fix this I would (1) rely on open-iscsi, or (2) update SourceName after installing the package but before running “isnsd —init”.

By the way, I get the error message:
> /etc/iscsi/initiatorname.iscsi: No such file or directory
but I don’t get the “Warning: …” messages when I test on Debian 10, FWIW.

— 
Lee Duncan

**Comment by rickysarraf** [comment]
> Yes, for initialization to complete, you need an initiator name. There are two ways to tell it your initiator name: 1. Populate the file /etc/iscsi/initiatorname.iscsi, or 2. Set the “SourceName” attribute in /etc/isns/isnsd.conf If you have both, I believe the one in isnsd.conf is used, which is why it is commented out by default.

Okay! THanks for this explanation. So the best is to have `open-iscsi` as a `Recommends` in Debian nomenclature, which is not a dependency strictly but rather a highly recommended option.

> There is no way to pass in an attribute in order to set this SourceName value on the fly. 

There is in Debian, in the form of pre and post installation script, which is why I sought your opinion on how the `isnsd` daemon behaves, by default.


> By the way, I get the error message:
> /etc/iscsi/initiatorname.iscsi: No such file or directory
> but I don’t get the “Warning: …” messages when I test on Debian 10, FWIW. — Lee Duncan

So the first error is understandable now. Perhaps `isnsd` shouldn't print that message with default log facility and instead only print in verbose mode.

For the 2nd error message, you don't get it on Debian 10 because Debian 10 uses an older version of `open-isns` at version `0.97`. Also to note is that that old version did not include support with OpenSSL.

The new version that I have prepared, which should be part of the next Debian stable release **Bullseye**, is now at version `0.100` and links to OpenSSL. And that is why you see those error messages from OpenSSL.

So far, as I understand, the OpenSSL routeine in `isnsd --init` also expects the public/private keys, without which they report this error message.

**Comment by rickysarraf** [comment]
So the problem is that, at first run, `isnsd --init` initialization code fails to generate a proper dsa key with openssl

```
rrs@priyasi:.../isns$ sudo isnsd --init
/etc/iscsi/initiatorname.iscsi: No such file or directory
Generating DSA parameters; this may take a while
+
Warning: Error generating DSA parameters - OpenSSL errors follow:
13:34 ♒ ॐ ♅ ♄ ⛢      ☹ 😟=> 1  
```


On the first run of the above, it generated a null file `/etc/isns/dsa.params`

```
rrs@priyasi:.../isns$ ls -lh
total 12K
-rw-r--r-- 1 root root    0 Dec  3 13:34 dsa.params
-rw-r--r-- 1 root root 2.0K Nov 23 22:37 isnsadm.conf
-rw-r--r-- 1 root root 3.7K Dec  3 13:33 isnsd.conf
-rw-r--r-- 1 root root 2.0K Dec  3 13:26 isnsdd.conf
13:37 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    
```

And then further runs on the `isnsd --init` daemon start to complain about the incorrect `dsa.params` file

```
rrs@priyasi:.../isns$ sudo isnsd --init
/etc/iscsi/initiatorname.iscsi: No such file or directory
Warning: Error loading DSA parameters - OpenSSL errors follow:
Warning: > get_name: no start line
Warning: Failed to generate AuthKey
13:38 ♒ ॐ ♅ ♄ ⛢      ☹ 😟=> 1  
```

**Comment by dholl** [comment]
Wow, the OpenSSL error looks like binary-interpretted-as-unicode vomit...
```13:34 ♒ ॐ ♅ ♄ ⛢      ☹ 😟=> 1```

I'm not familiar with this project, but I am interested in iSCSI & iSNS on Debian.  So, I thought I might suggest a couple quick-to-use tools that I find useful for extracting more diagnostic info.

My first tool is choice is ```strace```, such as:
```
sudo strace -DDD -f -o isnsd_init_strace.txt isnsd --init
```
(basically, just prefix your command with ```strace -DDD -f -o logfile.txt``` ...)

```strace``` will log all system calls (file open, close, read, write, exec, fork, etc...), which I find handy to figure out what specifically a process was attempting to do before it reports the error.  It glosses over library calls and other intermediate stuff though, and you may be interested in OpenSSL library calls...  (but ```strace``` works great even on statically compiled binaries)

So if strace doesn't help, and you really want to see what library calls are going on, then try ```ltrace```, such as
```
sudo ltrace -f -o isnsd_init_ltrace.txt isnsd --init
```
which traces library calls --- such as exploring OpenSSL functions is ```isnsd``` invoking.

If those don't help, then recompile with debug info and invoke your debugger-du-jour to step through source lines.  Hopefully, output from ltrace may give you some educated guesses on where to place breakpoints to inspect variables before the error.

**Comment by gonzoleeman** [comment]
> > Yes, for initialization to complete, you need an initiator name. There are two ways to tell it your initiator name: 1. Populate the file /etc/iscsi/initiatorname.iscsi, or 2. Set the “SourceName” attribute in /etc/isns/isnsd.conf If you have both, I believe the one in isnsd.conf is used, which is why it is commented out by default.
> 
> Okay! THanks for this explanation. So the best is to have `open-iscsi` as a `Recommends` in Debian nomenclature, which is not a dependency strictly but rather a highly recommended option.
> 
> > There is no way to pass in an attribute in order to set this SourceName value on the fly.
> 
> There is in Debian, in the form of pre and post installation script, which is why I sought your opinion on how the `isnsd` daemon behaves, by default.

No, you misunderstand. I was saying that there is no way to pass in SourceName on the command line when calling isnsd. So you would have to edit /etc/isns/isnsd.conf to set it.

> 
> > By the way, I get the error message:
> > /etc/iscsi/initiatorname.iscsi: No such file or directory
> > but I don’t get the “Warning: …” messages when I test on Debian 10, FWIW. — Lee Duncan
> 
> So the first error is understandable now. Perhaps `isnsd` shouldn't print that message with default log facility and instead only print in verbose mode.
> 
> For the 2nd error message, you don't get it on Debian 10 because Debian 10 uses an older version of `open-isns` at version `0.97`. Also to note is that that old version did not include support with OpenSSL.
> 
> The new version that I have prepared, which should be part of the next Debian stable release **Bullseye**, is now at version `0.100` and links to OpenSSL. And that is why you see those error messages from OpenSSL.

No, that does not appear to be correct. I just build and testing "isnsd --init" on my tumbleweed box (latest openSUSE), without the file /etc/iscsi/initiatorname.iscsi, and I did not get the verbose openSSL messages you got.

> 
> So far, as I understand, the OpenSSL routeine in `isnsd --init` also expects the public/private keys, without which they report this error message.

**Comment by gonzoleeman** [comment]
I just built and tested the latest open-isns on both Tumbleweed (SUSE) and Debian (RH), and in both cases "isnsd --init" does not work.

I get:

```
# ./isnsd --init -d all
/etc/iscsi/initiatorname.iscsi: No such file or directory
Generating DSA parameters; this may take a while
+
Warning: Error generating DSA parameters - OpenSSL errors follow:
```

Yes, this seems to be a result of the recent change I added that uses openssl. The whole reason for that change was so that open-isns would not have any crypto in it, and for auditing purposes that meant only libopenssl needed to be validated. But I have have to back out that change?

I apologize for this problem, but at SUSE we don't use the security in open-isns, i.e. it's compiled out. So I would never notice this problem. Actually, I'm not sure how many of my users even care about open-isns, sadly.

So it looks like you have (at least) two problems:
1. you need open-issn or a pre-install script to set up your initiator name, and
2. open-isns version 0.100 has a bug with "isnsd --init".

I will create a separate issue for #2.

**Comment by rickysarraf** [comment]
@gonzoleeman This is exactly the issue I have been talking about. I am glad you have finally been able to reproduce it locally.

For the first issue, that is not a big problem. As I mentioned earlier, the availability of the initiator name could be served through either by promoting `open-iscsi` to `Recommends` in Debian's terms. Or else, just inform the user to feed in a valid IQN during the installation phase of the `open-isns` pacakge.

**Comment by gonzoleeman** [comment]
I believe this is "fixed" for you now.

As far as the message:

`/etc/iscsi/initiatorname.iscsi: No such file or directory
`

You can either Recommend (or require) open-iscsi to make this message go away, or you can ignore it, since `isnsd --init `works even if you get this message:

```
/etc/iscsi/initiatorname.iscsi: No such file or directory
Generating DSA parameters; this may take a while
++++++++++++................................................................/.+.++++++.+++.+++.+++.++.+.++++++++++++++.++.+.++++++++++++++.+++.++++.++++.+++++++++++++++.+++++.+++++++++.++.++++++++++++++++++.+++++.+++.++++.+++++++++++++++.++++++++.++++++++.+++++++++++++++++++.+++++++++++++++++++++++++++++++.++++.++++++++.++++++++++++++++++++++++++.++++++++.+++++.++++.+++++++++++++.+++++++.+++++.+++++++++.+++++.+.+++.+++.++.++++++++++.++++++++++++++.++++++++++++++++++.++++++++++.++++.+++.++.+++.++++++++++++++++++++++.++.++++++++.+.++++++++++.++++++++++++++++.+++++++++++................................................................./
Stored private key in /etc/isns/auth_key
Stored private key in /etc/isns/auth_key.pub
```

As you can see, the initialization is no longer failing, so your distro can get update from upstream to fix your issues.

Please close this issue if you're okay with that. And thank you for finding this!

**Comment by rickysarraf** [comment]
Thank you @gonzoleeman 

With the fix you made, everything works perfect now.
