### ISSUE TITLE
Using meson instead of autoconf

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-isns#40]
See pull request #39 

Migrating to meson from autoconf. Please speak up if you have any issues.

**Comment by gonzoleeman** [comment]
My plan is to tag a new version once this is in place.

I'm actually thinking about upping the version number to 1.1

**Comment by hilaolu** [comment]
+1
I am trying to port open-isns to RISC-V architecture. However, config.ac seems to be too old to identify RISC-V as target.

```
This script, last modified 2005-05-27, has failed to recognize
the operating system you are using. It is advised that you
...
configure: error: cannot guess build type; you must specify one
```

Migrating to meson may help.

**Comment by gonzoleeman** [comment]
> +1 I am trying to port open-isns to RISC-V architecture. However, config.ac seems to be too old to identify RISC-V as target.
> 
> ```
> This script, last modified 2005-05-27, has failed to recognize
> the operating system you are using. It is advised that you
> ...
> configure: error: cannot guess build type; you must specify one
> ```
> 
> Migrating to meson may help.

Interesting.

Have you tried it yet? I did find internet references for cross-compiling for risc-v using meson: [link here](https://doc.dpdk.org/guides/linux_gsg/cross_build_dpdk_for_riscv.html). But nothing about just building on risc-v.

**Comment by eli-schwartz** [comment]
AFAIK Meson should work fine on risc-v, e.g.Debian builds a wide variety of Meson-based software on their risc-v port.

**Comment by hilaolu** [comment]
> > +1 I am trying to port open-isns to RISC-V architecture. However, config.ac seems to be too old to identify RISC-V as target.
> > ```
> > This script, last modified 2005-05-27, has failed to recognize
> > the operating system you are using. It is advised that you
> > ...
> > configure: error: cannot guess build type; you must specify one
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Migrating to meson may help.
> 
> Interesting.
> 
> Have you tried it yet? I did find internet references for cross-compiling for risc-v using meson: [link here](https://doc.dpdk.org/guides/linux_gsg/cross_build_dpdk_for_riscv.html). But nothing about just building on risc-v.

It builds just by running `autoreconf -fi` on build host(riscv64gc) to update `config.ac`.

**Comment by hilaolu** [comment]
It now builds painlessly with meson on RISC-V, thanks.

**Comment by gonzoleeman** [comment]
On Oct 2, 2022, at 8:30 PM, Phyzait Lu ***@***.***> wrote:
> 
> 
> It now builds painlessly with meson on RISC-V, thanks.
> 
That's great news!

— 
Lee

**Comment by gonzoleeman** [comment]
I am closing this issue as resolved. There are no Makefiles left now, nor any autoconf.
